# Sample workflow for building and deploying a Next.js site in the 'client' directory to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - develop  # Adjust the branch name as needed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build and deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Cache .next folder
        uses: actions/cache@v2
        with:
          path: client/.next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/.next', 'client/package-lock.json', 'client/yarn.lock') }}
          restore-keys: | 
            ${{ runner.os }}-nextjs-

      - name: Checkout
        uses: actions/checkout@v2

      - name: Change working directory to 'client'
        run: cd client  # Change to the 'client' directory

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use a Node.js version that suits your project

      - name: Install Yarn
        run: cd client && npm install -g yarn  # Specify the Yarn version you want to use


      - name: Install Project Dependencies with Yarn
        run: cd client && yarn install --frozen-lockfile

      - name: Debug package.json
        run: cat client/package.json

      - name: Build Project
        run: cd client && yarn build

      - name: Static HTML export with Next.js
        run: cd client && yarn next export -o ../out

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
