# Sample workflow for building and deploying a Next.js site in the 'client' directory to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build and deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Cache .next folder
        uses: actions/cache@v2
        with:
          path: client/.next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/.next', 'client/package-lock.json', 'client/yarn.lock') }}
          restore-keys: | 
            ${{ runner.os }}-nextjs-

      # Other steps (Checkout, Change working directory, Setup Node.js and Yarn, Install Project Dependencies) go here.


      - name: Checkout
        uses: actions/checkout@v2

      - name: Change working directory to 'client'
        run: cd client  # Change to the 'client' directory

      - name: Install Project Dependencies
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        
      - name: Build with Next.js
        run: yarn next build

      - name: Static HTML export with Next.js
        run: yarn next export -o ../out

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Update the path to point to the 'out' directory
          path: ../out
